/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FINALPROJECT;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author rammy
 */
public class StartScreen extends javax.swing.JFrame {
    private static String[][] EmployeeData = new String [10000][16];
    private static String[] data;
    private static int i = 1;

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jbAdd = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jbList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jlTitle.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jlTitle.setText("Broadhead Productions");

        jbAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAdd.setText("Add Employee");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jbEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbEdit.setText("Edit Employees");
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });

        jbList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbList.setText("List Employees");
        jbList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbList)
                            .addComponent(jbEdit))
                        .addGap(397, 397, 397))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jlTitle)
                .addGap(97, 97, 97)
                .addComponent(jbAdd)
                .addGap(82, 82, 82)
                .addComponent(jbEdit)
                .addGap(78, 78, 78)
                .addComponent(jbList)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String [][] GetData()
    {
        File f = new File("D:\\School\\High School\\Grade 12\\Employee\\Mock-Employee-Database\\FINAL PROJECT\\src\\FINALPROJECT\\EmployeeData.txt");
		
	// A BufferedReader is an object that lets you read a stream of Text Data
	BufferedReader in = null;
		
	// Try to open the file
	// Handle exceptions if they happen
	try {
            in = new BufferedReader(new FileReader(f));
	}
	catch (FileNotFoundException e){
            System.out.println("The file cannot be opened!  Error - " + e);
	}
		
	String line = null;
        boolean done = false;
        // Used to indicate when there's no more data in the file

        i=0;
	do {
            try
            { // Try to Read the next line from the file
                line = in.readLine();
            }
            catch (IOException e) 
            { //Handle any errors
		System.out.println("There is a problem at one of the lines. Error Number - " +e);
	    }
			  
            if (line == null || line.length() == 0)
            {
		done = true;  // No more data in the file - Your're done!  
            }
			  
            else 
            {
                i++;
                data = line.split(",");
                for (int j = 1; j <= 15; j++)
                    EmployeeData [i][j] = data [j-1];  

            }
	} while (!done);
        
        return EmployeeData;
    }
    
    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        // TODO add your handling code here:
        new AddPage(GetData()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAddActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        new EditPage(GetData()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbEditActionPerformed

    private void jbListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListActionPerformed
        // TODO add your handling code here:
        new ListPage(GetData()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbList;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
}
